### ISSUE TITLE
[FEAT] Process Showcase 

### ISSUE THREAD

**Issue by navaneethvenu** [dscmbcet/oogway#1]
Request for Process Showcase Feature, whereby multiple discord users may share their Process of Creation on the GDSC MBCET Discord Server, via live stream, while other users can view and learn along.

Features:

Each user must be able to use a command to create a voice channel with a specific Title, and Description, as well as interest roles.
Notifications must be sent to a #processShowcase Announcements channel, each time a processShowcase voice channel is created. @everyone must not be tagged, only those with the specific interest roles.
Care must be taken to ensure that there is no misuse of such privileges.
Multiple Users must be able to use the command to create their own processShowcase channels as well

**Comment by mak626** [comment]
Is the feature limited to the core team only or anyone in the members?
